def predict_price(address=None,
                  bedrooms=None,
                  full_bathrooms=None,
                  half_bathrooms=None,
                  _type=None,
                  size_sqft=None,
                  lot_size=None):
    """
        http://www.louisdorard.com/guest/everyone-can-do-data-science-bigml
        Predictor automatically generated by BigML
        Predictive model by BigML - Machine Learning Made Easy
    """

    import re

    tm_tokens = 'tokens_only'
    tm_full_term = 'full_terms_only'
    tm_all = 'all'

    def term_matches(text, field_name, term):
        """ Counts the number of occurences of term and its variants in text

        """
        forms_list = term_forms[field_name].get(term, [term])
        options = term_analysis[field_name]
        token_mode = options.get('token_mode', tm_tokens)
        case_sensitive = options.get('case_sensitive', False)
        first_term = forms_list[0]
        if token_mode == tm_full_term:
            return full_term_match(text, first_term, case_sensitive)
        else:
            # In token_mode='all' we will match full terms using equals and
            # tokens using contains
            if token_mode == tm_all and len(forms_list) == 1:
                pattern = re.compile(r'^.+\b.+$', re.U)
                if re.match(pattern, first_term):
                    return full_term_match(text, first_term, case_sensitive)
            return term_matches_tokens(text, forms_list, case_sensitive)


    def full_term_match(text, full_term, case_sensitive):
        """Counts the match for full terms according to the case_sensitive
              option

        """
        if not case_sensitive:
            text = text.lower()
            full_term = full_term.lower()
        return 1 if text == full_term else 0

    def get_tokens_flags(case_sensitive):
        """Returns flags for regular expression matching depending on text
              analysis options

        """
        flags = re.U
        if not case_sensitive:
            flags = (re.I | flags)
        return flags


    def term_matches_tokens(text, forms_list, case_sensitive):
        """ Counts the number of occurrences of the words in forms_list in
               the text

        """
        flags = get_tokens_flags(case_sensitive)
#        expression = ur'(\b|_)%s(\b|_)' % '(\\b|_)|(\\b|_)'.join(forms_list)
        expression = r'(\b|_)%s(\b|_)' % '(\\b|_)|(\\b|_)'.join(forms_list)
        pattern = re.compile(expression, flags=flags)
        matches = re.findall(pattern, text)
        return len(matches)


    term_analysis = {
        "size_sqft": {
            "token_mode": 'all',
            "case_sensitive": False,
        },
        "address": {
            "token_mode": 'all',
            "case_sensitive": False,
        },
    }
    term_forms = {
        "size_sqft": {
        },
        "address": {
        },
    }
    if (full_bathrooms is None):
        return 236622.9732
    if (full_bathrooms == '2.0'):
        if (half_bathrooms is None):
            return 181603.74232
        if (half_bathrooms == '0.0'):
            if (size_sqft is None):
                return 150545.3376
            if (term_matches(size_sqft, "size_sqft", "1657") > 0):
                return 535840
            if (term_matches(size_sqft, "size_sqft", "1657") <= 0):
                if (_type is None):
                    return 148183.01594
                if (_type == 'Single Family Home'):
                    if (lot_size is None):
                        return 175311.7027
                    if (lot_size == '207781.2'):
                        return 898900
                    if (lot_size != '207781.2'):
                        if (lot_size == '49222.8'):
                            return 575000
                        if (lot_size != '49222.8'):
                            if (address is None):
                                return 173928.35714
                            if (term_matches(address, "address", "las") > 0):
                                if (lot_size == '31363.2'):
                                    return 529000
                                if (lot_size != '31363.2'):
                                    if (lot_size == '23958.0'):
                                        return 479900
                                    if (lot_size != '23958.0'):
                                        if (lot_size == '90604.8'):
                                            return 450000
                                        if (lot_size != '90604.8'):
                                            if (lot_size == '165528.0'):
                                                return 449000
                                            if (lot_size != '165528.0'):
                                                if (lot_size == '20473.2'):
                                                    return 302099.75
                                                if (lot_size != '20473.2'):
                                                    if (lot_size == '95396.4'):
                                                        return 425000
                                                    if (lot_size != '95396.4'):
                                                        if (lot_size == '21780.0'):
                                                            return 332500
                                                        if (lot_size != '21780.0'):
                                                            if (bedrooms is None):
                                                                return 168337.51809
                                                            if (bedrooms == '2.0'):
                                                                if (term_matches(address, "address", "dr") > 0):
                                                                    return 228158.58974
                                                                if (term_matches(address, "address", "dr") <= 0):
                                                                    return 165262.35484
                                                            if (bedrooms != '2.0'):
                                                                if (lot_size == '5227.0'):
                                                                    return 203348.38235
                                                                if (lot_size != '5227.0'):
                                                                    if (lot_size == '21344.4'):
                                                                        return 255724.83333
                                                                    if (lot_size != '21344.4'):
                                                                        if (term_matches(address, "address", "89117") > 0):
                                                                            return 238198.88889
                                                                        if (term_matches(address, "address", "89117") <= 0):
                                                                            if (lot_size == '42688.8'):
                                                                                return 389900
                                                                            if (lot_size != '42688.8'):
                                                                                if (lot_size == '7840.0'):
                                                                                    return 195406.81579
                                                                                if (lot_size != '7840.0'):
                                                                                    if (term_matches(address, "address", "ct") > 0):
                                                                                        return 192388.80556
                                                                                    if (term_matches(address, "address", "ct") <= 0):
                                                                                        return 156312.29144
                            if (term_matches(address, "address", "las") <= 0):
                                return 249269.92593
                if (_type != 'Single Family Home'):
                    if (bedrooms is None):
                        return 121153.94492
                    if (bedrooms == '1.0'):
                        return 318369.89474
                    if (bedrooms != '1.0'):
                        if (_type == 'Single Family Home; Ready to build'):
                            return 360741.66667
                        if (_type != 'Single Family Home; Ready to build'):
                            if (lot_size is None):
                                return 114607.69571
                            if (lot_size == '2308.0'):
                                return 685000
                            if (lot_size != '2308.0'):
                                if (_type == 'Mfd/Mobile Home'):
                                    return 67591.54118
                                if (_type != 'Mfd/Mobile Home'):
                                    if (lot_size == '3049.0'):
                                        return 162227.26471
                                    if (lot_size != '3049.0'):
                                        if (lot_size == '7579.0'):
                                            return 304000
                                        if (lot_size != '7579.0'):
                                            if (lot_size == '4356.0'):
                                                return 152711.75
                                            if (lot_size != '4356.0'):
                                                return 102054.08502
        if (half_bathrooms != '0.0'):
            if (lot_size is None):
                return 224361.16023
            if (lot_size == '7840.0'):
                return 349410.16667
            if (lot_size != '7840.0'):
                if (_type is None):
                    return 215459.63321
                if (_type == 'Condo/Townhome/Row Home/Co-Op'):
                    if (lot_size == '2700.0'):
                        return 596626.66667
                    if (lot_size != '2700.0'):
                        if (lot_size == '2482.0'):
                            return 469900
                        if (lot_size != '2482.0'):
                            if (address is None):
                                return 131954.83471
                            if (term_matches(address, "address", "las") > 0):
                                if (lot_size == '2613.0'):
                                    return 201240
                                if (lot_size != '2613.0'):
                                    return 117876.92157
                            if (term_matches(address, "address", "las") <= 0):
                                return 211200.75
                if (_type != 'Condo/Townhome/Row Home/Co-Op'):
                    if (lot_size == '2178.0'):
                        return 155504.5625
                    if (lot_size != '2178.0'):
                        if (lot_size == '1742.0'):
                            return 144234.75556
                        if (lot_size != '1742.0'):
                            if (lot_size == '16552.8'):
                                return 779900
                            if (lot_size != '16552.8'):
                                if (bedrooms is None):
                                    return 232501.0954
                                if (bedrooms == '2.0'):
                                    return 323340.29032
                                if (bedrooms != '2.0'):
                                    if (lot_size == '27007.2'):
                                        return 697000
                                    if (lot_size != '27007.2'):
                                        if (lot_size == '55756.8'):
                                            return 679900
                                        if (lot_size != '55756.8'):
                                            if (lot_size == '2613.0'):
                                                return 179804.41892
                                            if (lot_size != '2613.0'):
                                                if (lot_size == '3484.0'):
                                                    return 193075.23684
                                                if (lot_size != '3484.0'):
                                                    if (lot_size == '174240.0'):
                                                        return 444930
                                                    if (lot_size != '174240.0'):
                                                        if (lot_size == '8712.0'):
                                                            return 323140.35294
                                                        if (lot_size != '8712.0'):
                                                            if (lot_size == '96267.6'):
                                                                return 549000
                                                            if (lot_size != '96267.6'):
                                                                if (lot_size == '3049.0'):
                                                                    return 197319.51923
                                                                if (lot_size != '3049.0'):
                                                                    if (lot_size == '3920.0'):
                                                                        return 208958.5679
                                                                    if (lot_size != '3920.0'):
                                                                        if (lot_size == '4791.0'):
                                                                            return 213170.01299
                                                                        if (lot_size != '4791.0'):
                                                                            if (lot_size == '4356.0'):
                                                                                return 218129.57143
                                                                            if (lot_size != '4356.0'):
                                                                                if (lot_size == '5227.0'):
                                                                                    return 224466.25
                                                                                if (lot_size != '5227.0'):
                                                                                    if (_type == 'Mfd/Mobile Home'):
                                                                                        return 104266.66667
                                                                                    if (_type != 'Mfd/Mobile Home'):
                                                                                        if (lot_size == '49658.4'):
                                                                                            return 525000
                                                                                        if (lot_size != '49658.4'):
                                                                                            if (lot_size == '18295.2'):
                                                                                                return 499999
                                                                                            if (lot_size != '18295.2'):
                                                                                                if (lot_size == '45302.4'):
                                                                                                    return 499900
                                                                                                if (lot_size != '45302.4'):
                                                                                                    if (lot_size == '23086.8'):
                                                                                                        return 499900
                                                                                                    if (lot_size != '23086.8'):
                                                                                                        if (lot_size == '19166.4'):
                                                                                                            return 489900
                                                                                                        if (lot_size != '19166.4'):
                                                                                                            if (lot_size == '23958.0'):
                                                                                                                return 489900
                                                                                                            if (lot_size != '23958.0'):
                                                                                                                return 261568.60727
    if (full_bathrooms != '2.0'):
        if (full_bathrooms == '1.0'):
            if (bedrooms is None):
                return 112636.59078
            if (bedrooms == '2.0'):
                if (lot_size is None):
                    return 76766.63636
                if (lot_size == '10018.8'):
                    return 349000
                if (lot_size != '10018.8'):
                    if (lot_size == '46609.2'):
                        return 320000
                    if (lot_size != '46609.2'):
                        return 72883.29167
            if (bedrooms != '2.0'):
                if (half_bathrooms is None):
                    return 126955.64516
                if (half_bathrooms == '0.0'):
                    if (address is None):
                        return 107427.69474
                    if (term_matches(address, "address", "ave") > 0):
                        return 146224.55263
                    if (term_matches(address, "address", "ave") <= 0):
                        if (term_matches(address, "address", "st") > 0):
                            return 44033
                        if (term_matches(address, "address", "st") <= 0):
                            if (_type is None):
                                return 103607.54745
                            if (_type == 'Mfd/Mobile Home'):
                                return 325000
                            if (_type != 'Mfd/Mobile Home'):
                                return 101979.66176
                if (half_bathrooms != '0.0'):
                    if (address is None):
                        return 190926.51724
                    if (term_matches(address, "address", "rd") > 0):
                        return 459749.75
                    if (term_matches(address, "address", "rd") <= 0):
                        if (term_matches(address, "address", "unit") > 0):
                            return 252819.15789
                        if (term_matches(address, "address", "unit") <= 0):
                            return 126605
        if (full_bathrooms != '1.0'):
            if (half_bathrooms is None):
                return 377781.77786
            if (half_bathrooms == '0.0'):
                if (full_bathrooms == '3.0'):
                    if (address is None):
                        return 292707.10263
                    if (term_matches(address, "address", "unit") > 0):
                        if (term_matches(address, "address", "rd") > 0):
                            return 954333
                        if (term_matches(address, "address", "rd") <= 0):
                            if (term_matches(address, "address", "ave") > 0):
                                return 599925.33333
                            if (term_matches(address, "address", "ave") <= 0):
                                return 261704
                    if (term_matches(address, "address", "unit") <= 0):
                        if (term_matches(address, "address", "89122") > 0):
                            return 164149
                        if (term_matches(address, "address", "89122") <= 0):
                            if (lot_size is None):
                                return 293052.86579
                            if (lot_size == '3920.0'):
                                return 207323.86486
                            if (lot_size != '3920.0'):
                                if (lot_size == '16552.8'):
                                    return 657500
                                if (lot_size != '16552.8'):
                                    if (lot_size == '15246.0'):
                                        return 649999.5
                                    if (lot_size != '15246.0'):
                                        if (term_matches(address, "address", "las") > 0):
                                            if (lot_size == '3484.0'):
                                                return 200963.63636
                                            if (lot_size != '3484.0'):
                                                if (term_matches(address, "address", "ct") > 0):
                                                    if (lot_size == '17859.6'):
                                                        return 622400
                                                    if (lot_size != '17859.6'):
                                                        if (lot_size == '8276.0'):
                                                            return 461358.16667
                                                        if (lot_size != '8276.0'):
                                                            if (lot_size == '10454.4'):
                                                                return 639000
                                                            if (lot_size != '10454.4'):
                                                                if (lot_size == '4356.0'):
                                                                    return 185675
                                                                if (lot_size != '4356.0'):
                                                                    if (lot_size == '19602.0'):
                                                                        return 575000
                                                                    if (lot_size != '19602.0'):
                                                                        if (lot_size == '2613.0'):
                                                                            return 141500
                                                                        if (lot_size != '2613.0'):
                                                                            if (lot_size == '20037.6'):
                                                                                return 524900
                                                                            if (lot_size != '20037.6'):
                                                                                return 319181.95402
                                                if (term_matches(address, "address", "ct") <= 0):
                                                    if (lot_size == '5532.0'):
                                                        return 695000
                                                    if (lot_size != '5532.0'):
                                                        if (lot_size == '130680.0'):
                                                            return 374644.5
                                                        if (lot_size != '130680.0'):
                                                            if (bedrooms is None):
                                                                return 285563.59455
                                                            if (bedrooms == '5.0'):
                                                                if (lot_size == '9583.0'):
                                                                    return 443233.33333
                                                                if (lot_size != '9583.0'):
                                                                    if (lot_size == '12632.4'):
                                                                        return 412475
                                                                    if (lot_size != '12632.4'):
                                                                        if (term_matches(address, "address", "89117") > 0):
                                                                            return 355370.57143
                                                                        if (term_matches(address, "address", "89117") <= 0):
                                                                            return 296930.17297
                                                            if (bedrooms != '5.0'):
                                                                if (lot_size == '30492.0'):
                                                                    return 642900
                                                                if (lot_size != '30492.0'):
                                                                    if (_type is None):
                                                                        return 272682.81924
                                                                    if (_type == 'Single Family Home'):
                                                                        if (lot_size == '16117.2'):
                                                                            return 447600
                                                                        if (lot_size != '16117.2'):
                                                                            if (lot_size == '31798.8'):
                                                                                return 570000
                                                                            if (lot_size != '31798.8'):
                                                                                if (lot_size == '22215.6'):
                                                                                    return 421373.75
                                                                                if (lot_size != '22215.6'):
                                                                                    if (lot_size == '12632.4'):
                                                                                        return 519950
                                                                                    if (lot_size != '12632.4'):
                                                                                        if (lot_size == '22651.2'):
                                                                                            return 519000
                                                                                        if (lot_size != '22651.2'):
                                                                                            if (lot_size == '34412.4'):
                                                                                                return 499000
                                                                                            if (lot_size != '34412.4'):
                                                                                                if (lot_size == '20037.6'):
                                                                                                    return 354657.14286
                                                                                                if (lot_size != '20037.6'):
                                                                                                    if (term_matches(address, "address", "89108") > 0):
                                                                                                        return 183981.25
                                                                                                    if (term_matches(address, "address", "89108") <= 0):
                                                                                                        if (lot_size == '17424.0'):
                                                                                                            return 489000
                                                                                                        if (lot_size != '17424.0'):
                                                                                                            if (lot_size == '11325.6'):
                                                                                                                return 388300
                                                                                                            if (lot_size != '11325.6'):
                                                                                                                if (lot_size == '13068.0'):
                                                                                                                    return 414949.5
                                                                                                                if (lot_size != '13068.0'):
                                                                                                                    return 266927.80333
                                                                    if (_type != 'Single Family Home'):
                                                                        return 170670.18182
                                        if (term_matches(address, "address", "las") <= 0):
                                            return 408628.94737
                if (full_bathrooms != '3.0'):
                    if (full_bathrooms == '5.0'):
                        return 564023
                    if (full_bathrooms != '5.0'):
                        if (lot_size is None):
                            return 436239.52308
                        if (lot_size == '24829.2'):
                            return 900000
                        if (lot_size != '24829.2'):
                            if (lot_size == '23522.4'):
                                return 692500
                            if (lot_size != '23522.4'):
                                if (address is None):
                                    return 428552.26772
                                if (term_matches(address, "address", "rd") > 0):
                                    return 250970
                                if (term_matches(address, "address", "rd") <= 0):
                                    if (lot_size == '17424.0'):
                                        return 799000
                                    if (lot_size != '17424.0'):
                                        if (lot_size == '87120.0'):
                                            return 292242.5
                                        if (lot_size != '87120.0'):
                                            if (term_matches(address, "address", "ave") > 0):
                                                return 386215.70833
                                            if (term_matches(address, "address", "ave") <= 0):
                                                if (lot_size == '14374.8'):
                                                    return 859900
                                                if (lot_size != '14374.8'):
                                                    if (lot_size == '3484.0'):
                                                        return 297663
                                                    if (lot_size != '3484.0'):
                                                        if (lot_size == '44866.8'):
                                                            return 699880
                                                        if (lot_size != '44866.8'):
                                                            if (term_matches(address, "address", "st") > 0):
                                                                return 393842.33333
                                                            if (term_matches(address, "address", "st") <= 0):
                                                                if (lot_size == '10018.8'):
                                                                    return 799900
                                                                if (lot_size != '10018.8'):
                                                                    if (lot_size == '20037.6'):
                                                                        return 684450
                                                                    if (lot_size != '20037.6'):
                                                                        if (bedrooms is None):
                                                                            return 453779.42188
                                                                        if (bedrooms == '5.0'):
                                                                            return 475906.46341
                                                                        if (bedrooms != '5.0'):
                                                                            return 414335.56522
            if (half_bathrooms != '0.0'):
                if (full_bathrooms == '3.0'):
                    if (lot_size is None):
                        return 444943.15278
                    if (lot_size == '1742.0'):
                        return 170803.57143
                    if (lot_size != '1742.0'):
                        if (lot_size == '2178.0'):
                            return 176783.33333
                        if (lot_size != '2178.0'):
                            if (lot_size == '5662.0'):
                                return 296740
                            if (lot_size != '5662.0'):
                                if (lot_size == '40075.2'):
                                    return 999000
                                if (lot_size != '40075.2'):
                                    if (lot_size == '84070.8'):
                                        return 989000
                                    if (lot_size != '84070.8'):
                                        if (lot_size == '12196.8'):
                                            return 719500
                                        if (lot_size != '12196.8'):
                                            if (lot_size == '2613.0'):
                                                return 99999.5
                                            if (lot_size != '2613.0'):
                                                if (lot_size == '13939.2'):
                                                    return 670309.8
                                                if (lot_size != '13939.2'):
                                                    if (lot_size == '35719.2'):
                                                        return 898076
                                                    if (lot_size != '35719.2'):
                                                        if (lot_size == '87991.2'):
                                                            return 885000
                                                        if (lot_size != '87991.2'):
                                                            if (lot_size == '6098.0'):
                                                                if (bedrooms is None):
                                                                    return 373052.66667
                                                                if (bedrooms == '6.0'):
                                                                    return 229200
                                                                if (bedrooms != '6.0'):
                                                                    return 386130.18182
                                                            if (lot_size != '6098.0'):
                                                                if (lot_size == '5227.0'):
                                                                    return 310286.25
                                                                if (lot_size != '5227.0'):
                                                                    if (lot_size == '4791.0'):
                                                                        return 220000
                                                                    if (lot_size != '4791.0'):
                                                                        if (lot_size == '3049.0'):
                                                                            return 284640.5
                                                                        if (lot_size != '3049.0'):
                                                                            if (address is None):
                                                                                return 475758.44608
                                                                            if (term_matches(address, "address", "ct") > 0):
                                                                                return 528685.24324
                                                                            if (term_matches(address, "address", "ct") <= 0):
                                                                                if (lot_size == '18730.8'):
                                                                                    return 717456
                                                                                if (lot_size != '18730.8'):
                                                                                    if (term_matches(address, "address", "dr") > 0):
                                                                                        return 531056.20833
                                                                                    if (term_matches(address, "address", "dr") <= 0):
                                                                                        if (lot_size == '16552.8'):
                                                                                            return 799000
                                                                                        if (lot_size != '16552.8'):
                                                                                            if (lot_size == '49658.4'):
                                                                                                return 775000
                                                                                            if (lot_size != '49658.4'):
                                                                                                if (lot_size == '9147.0'):
                                                                                                    return 322566.66667
                                                                                                if (lot_size != '9147.0'):
                                                                                                    if (lot_size == '46173.6'):
                                                                                                        return 720000
                                                                                                    if (lot_size != '46173.6'):
                                                                                                        if (lot_size == '22651.2'):
                                                                                                            return 598333.33333
                                                                                                        if (lot_size != '22651.2'):
                                                                                                            if (lot_size == '3920.0'):
                                                                                                                return 262450
                                                                                                            if (lot_size != '3920.0'):
                                                                                                                if (lot_size == '174240.0'):
                                                                                                                    return 613490
                                                                                                                if (lot_size != '174240.0'):
                                                                                                                    if (lot_size == '20037.6'):
                                                                                                                        return 508915.27273
                                                                                                                    if (lot_size != '20037.6'):
                                                                                                                        if (lot_size == '8712.0'):
                                                                                                                            return 530815.83333
                                                                                                                        if (lot_size != '8712.0'):
                                                                                                                            if (lot_size == '19602.0'):
                                                                                                                                return 645812
                                                                                                                            if (lot_size != '19602.0'):
                                                                                                                                if (lot_size == '18295.2'):
                                                                                                                                    return 553666.66667
                                                                                                                                if (lot_size != '18295.2'):
                                                                                                                                    if (lot_size == '11325.6'):
                                                                                                                                        return 225000
                                                                                                                                    if (lot_size != '11325.6'):
                                                                                                                                        if (term_matches(address, "address", "89108") > 0):
                                                                                                                                            return 225000
                                                                                                                                        if (term_matches(address, "address", "89108") <= 0):
                                                                                                                                            return 431343.65686
                if (full_bathrooms != '3.0'):
                    if (full_bathrooms == '4.0'):
                        if (lot_size is None):
                            return 565911.125
                        if (lot_size == '14810.4'):
                            return 834700
                        if (lot_size != '14810.4'):
                            if (lot_size == '10890.0'):
                                return 867999.66667
                            if (lot_size != '10890.0'):
                                if (lot_size == '20908.8'):
                                    return 912500
                                if (lot_size != '20908.8'):
                                    if (lot_size == '6969.0'):
                                        return 339580
                                    if (lot_size != '6969.0'):
                                        if (lot_size == '91476.0'):
                                            return 1000000
                                        if (lot_size != '91476.0'):
                                            if (address is None):
                                                return 550585.29457
                                            if (term_matches(address, "address", "89117") > 0):
                                                return 700097.5
                                            if (term_matches(address, "address", "89117") <= 0):
                                                if (lot_size == '179902.8'):
                                                    return 919999
                                                if (lot_size != '179902.8'):
                                                    if (lot_size == '6098.0'):
                                                        return 389800
                                                    if (lot_size != '6098.0'):
                                                        if (lot_size == '6534.0'):
                                                            return 400758
                                                        if (lot_size != '6534.0'):
                                                            if (lot_size == '22651.2'):
                                                                return 865000
                                                            if (lot_size != '22651.2'):
                                                                if (lot_size == '15246.0'):
                                                                    return 726333.33333
                                                                if (lot_size != '15246.0'):
                                                                    if (lot_size == '46173.6'):
                                                                        return 849900
                                                                    if (lot_size != '46173.6'):
                                                                        if (bedrooms is None):
                                                                            return 539600.32381
                                                                        if (bedrooms == '4.0'):
                                                                            return 596132.875
                                                                        if (bedrooms != '4.0'):
                                                                            if (lot_size == '7405.0'):
                                                                                return 374333.33333
                                                                            if (lot_size != '7405.0'):
                                                                                if (lot_size == '20037.6'):
                                                                                    return 658402.66667
                                                                                if (lot_size != '20037.6'):
                                                                                    if (lot_size == '10018.8'):
                                                                                        return 756000
                                                                                    if (lot_size != '10018.8'):
                                                                                        if (term_matches(address, "address", "rd") > 0):
                                                                                            return 318351
                                                                                        if (term_matches(address, "address", "rd") <= 0):
                                                                                            if (term_matches(address, "address", "89129") > 0):
                                                                                                return 410962.66667
                                                                                            if (term_matches(address, "address", "89129") <= 0):
                                                                                                return 527791.4
                    if (full_bathrooms != '4.0'):
                        return 720350.4375


if __name__ == '__main__':
    print('begin')
    print(predict_price(bedrooms=2))
    print(predict_price(bedrooms=0,size_sqft=100,full_bathrooms=2))


